---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url: 
sections:
- type: heading
  label: Injoon Oh's Website
upload_dir: uploads
public_path: "/public/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
